### ISSUE TITLE
Volume data already exist in /home/dokku/.o_volume, installation aborded 

### ISSUE THREAD

**Issue by iamso** [ohardy/dokku-volume#5]
Everytime I run `dokku plugins-install`, i get the following error:
```
Volume data already exist in /home/dokku/.o_volume, installation aborded 
```
So basically, after I install this plugin, I can't install any other plugins. I always have to delete the o_volume directory to contiune.

Is there anything I can do? Or is this a bug?

**Comment by ohardy** [comment]
It's just a message, you don't have to delete the o_volume directory. I will remove this message soon ;)

**Comment by soDEVch** [comment]
It must be more than a message, because it actually stops the plugins-install process.

**Comment by ohardy** [comment]
Sorry, forgot that it was already fixed in last version, just git pull in the plugin directory

**Comment by iamso** [comment]
Ok, seems to be fixed. Thx.
