### ISSUE TITLE
dokku-volume plugin should use DOKKU_NOT_IMPLEMENTED_EXIT if command not valid

### ISSUE THREAD

**Issue by fwolfst** [ohardy/dokku-volume#7]
Hi and thanks for your plugin, looks really useful.

To stay friendly to users it should use DOKKU_NOT_IMPLEMENTED_EXIT when it does not handle the given command like mentioned in

https://github.com/Kloadut/dokku-pg-plugin/issues/72 (simple fix given)
and
https://github.com/progrium/dokku/issues/1156

Thanks again
Felix

**Comment by ohardy** [comment]
Merged, thanks for that and sorry for the time that i took, was little busy ;)
